import { z } from 'zod';

// ============================================================
// Tool Schema — what an agent can use
// ============================================================
export const ToolSchema = z.object({
  name: z.string().min(1),
  type: z.enum(['api', 'database', 'file_system', 'notification', 'web_search', 'llm_reasoning', 'social_media', 'scraping', 'crm', 'analytics', 'messaging']),
  requiresAuth: z.boolean().default(false),
  confidentialityLevel: z.enum(['public', 'internal', 'confidential', 'restricted']).default('internal'),
  config: z.record(z.string(), z.unknown()).optional(),
});

// ============================================================
// Agent Definition — a single agent within a mission
// ============================================================
export const AgentDefinitionSchema = z.object({
  id: z.string().uuid(),
  role: z.string().min(1),
  agentIndex: z.number().int().min(0),
  capabilities: z.array(z.string()).min(1),
  requiresExternalData: z.boolean().default(false),
  tools: z.array(ToolSchema).default([]),
  systemPrompt: z.string().optional().default(""),
  handoffProtocol: z.string().optional(),
  pythonScript: z.string().optional(),
  trustLevel: z.enum(['autonomous', 'conditional', 'manual']).default('autonomous'),
});

// ============================================================
// Orchestration Edge — connection between two agents
// ============================================================
export const EdgeSchema = z.object({
  from: z.string().uuid(),
  to: z.string().uuid(),
  condition: z.string().optional(),
});

// ============================================================
// Orchestration Config — how agents coordinate
// ============================================================
export const OrchestrationSchema = z.object({
  pattern: z.enum(['sequential', 'parallel', 'orchestrator_worker', 'hierarchical']),
  timeoutSeconds: z.number().int().min(30).default(300),
  entryAgent: z.string().uuid(),
  edges: z.array(EdgeSchema),
});

// ============================================================
// Permission Requirement — what credentials are needed
// ============================================================
export const PermissionRequirementSchema = z.object({
  type: z.enum(['api_key', 'oauth_token', 'database_credential', 'file_access', 'service_account', 'webhook']),
  service: z.string().min(1),
  scope: z.string().min(1),
  confidentialityLevel: z.enum(['public', 'internal', 'confidential', 'restricted']),
  granted: z.boolean().default(false),
});

// ============================================================
// Mission JSON — the complete mission specification
// Generated by the LLM intake layer, validated by Zod.
// ============================================================
export const MissionSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string().uuid(),
  title: z.string().min(1),
  description: z.string().min(1),
  status: z.enum([
    'draft',
    'pending_permissions',
    'pending_validation',
    'pending_approval',
    'building',
    'active',
    'paused',
    'completed',
    'failed',
    'deadlocked',
  ]).default('draft'),
  agents: z.array(AgentDefinitionSchema).min(1, 'At least one agent is required'),
  orchestration: OrchestrationSchema,
  validationChecklist: z.array(z.string()).min(1, 'At least one validation check is required'),
  expectedOutputFormat: z.string().optional(),
  permissions: z.array(PermissionRequirementSchema).default([]),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

// ============================================================
// LLM Output Schema — what the LLM returns (no id/tenantId/timestamps)
// The intake service adds those fields after validation.
// ============================================================
export const LLMOutputSchema = z.object({
  title: z.string().min(1),
  description: z.string().min(1),
  agents: z.array(
    AgentDefinitionSchema.omit({ id: true, systemPrompt: true }).extend({
      id: z.string().uuid().optional(),
      systemPrompt: z.string().optional(),
      handoffProtocol: z.string().optional(),
      pythonScript: z.string().optional(),
    })
  ).min(1),
  orchestration: z.object({
    pattern: z.enum(['sequential', 'parallel', 'orchestrator_worker', 'hierarchical']),
    timeoutSeconds: z.number().int().min(30).default(300),
    entryAgent: z.string().optional(),
    edges: z.array(
      z.object({
        from: z.string(),
        to: z.string(),
        condition: z.string().optional(),
      })
    ).default([]),
  }),
  validationChecklist: z.array(z.string()).min(1),
  expectedOutputFormat: z.string().optional(),
  permissions: z.array(PermissionRequirementSchema).default([]),
  discoveryQuestions: z.array(z.string()).min(3).default([]),
});

// ============================================================
// Type exports
// ============================================================
export type Mission = z.infer<typeof MissionSchema>;
export type LLMOutput = z.infer<typeof LLMOutputSchema>;
export type AgentDefinition = z.infer<typeof AgentDefinitionSchema>;
export type Orchestration = z.infer<typeof OrchestrationSchema>;
export type PermissionRequirement = z.infer<typeof PermissionRequirementSchema>;
export type Tool = z.infer<typeof ToolSchema>;
