import { NonRetriableError } from 'inngest';
import { inngest } from './client';
import { createServiceClient } from '@/lib/supabase/server';
import { executeAgent } from '@/lib/services/runtime/agent-loop';
import { transitionMissionStatus } from '@/lib/services/orchestrator';

// ═══════════════════════════════════════════════════════════
// Inngest Function: Execute Mission in Background
//
// Each agent runs as a separate Inngest "step" with its own
// timeout (5 min). No more Vercel function timeouts!
//
// runId is generated by the caller (scheduler, webhook trigger,
// or manual fire) so it matches the mission_runs row that was
// created before the Inngest event was sent. This is also what
// fixes the recurring-mission bug: the resume check now filters
// agent.completed events by run_id, so run #2 never sees run
// #1's completed events and skips all agents.
// ═══════════════════════════════════════════════════════════

export const executeMissionBackground = inngest.createFunction(
  {
    id: 'execute-mission',
    name: 'Execute Mission (Background)',
    retries: 1,
    cancelOn: [
      { event: 'mission.cancel', match: 'data.missionId' },
    ],
    triggers: [{ event: 'mission.execute' }],
  },
  async ({ event, step }) => {
    const { missionId, tenantId, runId: incomingRunId, trigger: incomingTrigger, webhookPayload } = event.data;

    // ── Step 1: Fetch mission data + initialise run tracking ──
    const missionData = await step.run('fetch-mission', async () => {
      const supabase = createServiceClient();

      const { data: missionRow, error } = await supabase
        .from('missions')
        .select('mission_json')
        .eq('id', missionId)
        .eq('tenant_id', tenantId)
        .single();

      if (error || !missionRow) throw new Error(`Mission ${missionId} not found.`);

      const { data: userTokensRow } = await supabase
        .from('tenant_permissions')
        .select('provider')
        .eq('tenant_id', tenantId);

      const { getValidTokens } = await import('@/lib/services/oauth-refresher');
      const tokens: { provider: string; access_token: string }[] = [];

      if (userTokensRow) {
        for (const t of userTokensRow) {
          const validToken = await getValidTokens(tenantId, t.provider);
          if (validToken) tokens.push(validToken);
        }
      }

      // Use runId from the caller (scheduler/webhook), or generate one here.
      // The mission_runs row must be created if it doesn't exist yet
      // (manual executions that bypass executor.ts come in without a pre-created row).
      const runId: string = incomingRunId ?? crypto.randomUUID();
      const trigger: string = incomingTrigger ?? 'manual';

      const { count: priorRuns } = await supabase
        .from('mission_runs')
        .select('*', { count: 'exact', head: true })
        .eq('mission_id', missionId);
      const runNumber = (priorRuns ?? 0) + 1;

      // Upsert the mission_runs row — if it was already created by the caller, this is a no-op.
      const { error: runErr } = await supabase.from('mission_runs').upsert({
        id: runId,
        tenant_id: tenantId,
        mission_id: missionId,
        run_number: runNumber,
        trigger,
        status: 'running',
        agents_total: missionRow.mission_json.agents?.length ?? 0,
        agents_done: 0,
        agents_failed: 0,
      }, { onConflict: 'id', ignoreDuplicates: true });
      if (runErr) console.warn('[Inngest] Failed to upsert mission_runs row (non-fatal):', runErr.message);

      // ── Build initial context for the first agent ──

      // 1. Webhook payload: the POST body becomes the first agent's input so
      //    agents can act on the incoming data (new row, form submission, etc.)
      let initialContext = '';
      if (trigger === 'webhook' && webhookPayload) {
        const formatted = typeof webhookPayload === 'string'
          ? webhookPayload
          : JSON.stringify(webhookPayload, null, 2);
        initialContext = `WEBHOOK TRIGGER DATA:\n${formatted}`;
      }

      // 2. Cross-run memory: for recurring runs (#2+), inject the previous
      //    completed run's summary so agents know what they did last time and
      //    can avoid repeating work (e.g. skip already-processed leads).
      if (runNumber > 1) {
        const { data: lastRun } = await supabase
          .from('mission_runs')
          .select('run_number, started_at, agents_done, agents_total, summary')
          .eq('mission_id', missionId)
          .eq('status', 'completed')
          .order('started_at', { ascending: false })
          .limit(1)
          .single();

        if (lastRun) {
          const prevDate = new Date(lastRun.started_at).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
          const prevLines = [
            `PREVIOUS RUN CONTEXT (Run #${lastRun.run_number} — ${prevDate}):`,
            `- Agents completed: ${lastRun.agents_done}/${lastRun.agents_total}`,
            ...(lastRun.summary ? [`- Summary: ${typeof lastRun.summary === 'string' ? lastRun.summary : JSON.stringify(lastRun.summary)}`] : []),
            `Use this context to avoid repeating work already done in prior runs.`,
          ].join('\n');
          initialContext = initialContext
            ? `${prevLines}\n\n${initialContext}`
            : prevLines;
        }
      }

      return { mission: missionRow.mission_json, tokens, runId, trigger, runNumber, initialContext };
    });

    const { mission, tokens, runId, trigger, runNumber, initialContext } = missionData;
    const orchestration = mission.orchestration;
    const agents = mission.agents;
    const agentMap = new Map<string, any>(agents.map((a: any) => [a.id, a]));

    const startedAt = Date.now();
    let currentAgentId: string | null = orchestration.entryAgent;
    // Seed the first agent's context with webhook payload and/or previous-run memory
    let currentContext = initialContext ?? '';
    let agentsDone = 0;
    let agentsFailed = 0;

    const updateRun = async (updates: Record<string, unknown>) => {
      const supabase = createServiceClient();
      const { error } = await supabase.from('mission_runs').update(updates).eq('id', runId);
      if (error) console.warn('[Inngest] Failed to update mission_runs (non-fatal):', error.message);
    };

    try {
      while (currentAgentId) {
        const agent = agentMap.get(currentAgentId);
        if (!agent) throw new Error(`Agent ${currentAgentId} not found in mission graph.`);

        const agentToRun = agent;
        const contextForAgent = currentContext;
        const agentId = currentAgentId;

        const outEdges = orchestration.edges?.filter((e: any) => e.from === agentId) || [];
        const isFinalAgent = outEdges.length === 0 && orchestration.pattern !== 'supervisor';

        // ── Each agent runs as its own Inngest step (own 5-min timeout) ──
        const agentResult = await step.run(`agent-${agentToRun.role.replace(/\s+/g, '-').toLowerCase()}`, async () => {
          console.log(`[Inngest] Starting agent: ${agentToRun.role} (${agentToRun.id})`);

          const supabase = createServiceClient();

          // Resume check: filter by run_id so run #2 never reuses run #1's outputs.
          const { data: existingEvents } = await supabase
            .from('events')
            .select('payload')
            .eq('tenant_id', tenantId)
            .eq('event_type', 'agent.completed')
            .eq('entity_id', agentToRun.id)
            .eq('run_id', runId)
            .order('created_at', { ascending: false })
            .limit(1);

          if (existingEvents?.length && existingEvents[0].payload.output) {
            console.log(`[Inngest] Agent ${agentToRun.role} already completed in this run. Using cached output.`);
            return { output: existingEvents[0].payload.output, finalCode: agentToRun.pythonScript || '', resumed: true };
          }

          // Credit check — must cover minimum sandbox (8) + flash LLM (4) = 12 credits
          const { checkCredits, CREDIT_COSTS } = await import('@/lib/middleware/billing');
          const creditCheck = await checkCredits(tenantId, CREDIT_COSTS.code_execution + CREDIT_COSTS.llm_call_flash);
          if (!creditCheck.allowed) {
            console.log(`[Inngest] Insufficient credits for agent ${agentToRun.role}. Pausing.`);
            await transitionMissionStatus(missionId, tenantId, 'paused');
            throw new Error('InsufficientCredits');
          }

          const result = await executeAgent(
            tenantId, missionId, agentToRun, contextForAgent, tokens, isFinalAgent, mission.expectedOutputFormat, runId
          );

          // Code lock
          if (result.finalCode && result.finalCode !== agentToRun.pythonScript) {
            console.log(`[Inngest] Code healed for Agent ${agentToRun.id}. Locking into blueprint.`);
            const { data: missionData } = await supabase
              .from('missions')
              .select('mission_json')
              .eq('id', missionId)
              .single();
            if (missionData?.mission_json) {
              const blueprint = missionData.mission_json;
              const agentNode = blueprint.agents?.find((n: any) => n.id === agentToRun.id);
              if (agentNode) {
                agentNode.pythonScript = result.finalCode;
                await supabase.from('missions').update({ mission_json: blueprint }).eq('id', missionId);
              }
            }
          }

          return { ...result, resumed: false };
        });

        if (agentResult.resumed) agentsDone++;
        else agentsDone++;

        const output = agentResult.output;

        // ── Orchestration: Determine next agent ──
        if (orchestration.pattern === 'supervisor' || orchestration.pattern === 'orchestrator_worker') {
          const nextAgent = await step.run(`supervisor-decision-after-${agent.role.replace(/\s+/g, '-')}`, async () => {
            const { callLLM, getModelCreditCost } = await import('@/lib/services/llm-router');
            const availableAgents = agents
              .map((a: any) => ({ id: a.id, role: a.role }))
              .filter((a: any) => a.id !== agentId);
            const decision = await callLLM([
              { role: 'system', content: `You are the Mission Supervisor. Based on the previous agent's output, decide which agent should run next. If the goal is fully achieved, return null. Return JSON: {"nextAgentId": "uuid-here" | null, "reasoning": "why"}` },
              { role: 'user', content: `Mission: ${mission.title}\n\nAvailable Agents:\n${JSON.stringify(availableAgents, null, 2)}\n\nPrevious Agent Output:\n${output}` }
            ], { jsonMode: true, tier: 2 });
            // Bill supervisor routing call
            try {
              const { deductCredits } = await import('@/lib/middleware/billing');
              await deductCredits(tenantId, getModelCreditCost(decision.model), `supervisor_routing:${agentId}`);
            } catch { /* non-fatal */ }
            return JSON.parse(decision.content);
          });
          currentAgentId = nextAgent.nextAgentId;
          currentContext = output;

        } else if (orchestration.pattern === 'parallel') {
          const parallelEdges = orchestration.edges.filter((e: any) => e.from === agentId);
          if (parallelEdges.length > 1) {
            const parallelResults = await step.run(`parallel-fanout-from-${agent.role.replace(/\s+/g, '-')}`, async () => {
              const results = await Promise.allSettled(
                parallelEdges.map(async (edge: any) => {
                  const pAgent = agentMap.get(edge.to);
                  if (!pAgent) throw new Error(`Agent ${edge.to} not found`);
                  const pOutEdges = orchestration.edges?.filter((e: any) => e.from === pAgent.id) || [];
                  const pIsFinal = pOutEdges.length === 0;
                  const result = await executeAgent(tenantId, missionId, pAgent, output, tokens, pIsFinal, mission.expectedOutputFormat, runId);
                  return { agentId: edge.to, role: pAgent.role, output: result.output };
                })
              );
              return results.map(r =>
                r.status === 'fulfilled' ? r.value : { error: (r as PromiseRejectedResult).reason?.message || 'Agent failed' }
              );
            });
            for (const r of parallelResults) {
              if ('error' in r) agentsFailed++; else agentsDone++;
            }
            currentContext = JSON.stringify(parallelResults);
            const parallelTargets = new Set(parallelEdges.map((e: any) => e.to));
            const gatherEdge = orchestration.edges.find((e: any) =>
              parallelTargets.has(e.from) && !parallelTargets.has(e.to)
            );
            currentAgentId = gatherEdge?.to || null;
          } else if (parallelEdges.length === 1) {
            currentAgentId = parallelEdges[0].to;
            currentContext = output;
          } else {
            currentAgentId = null;
          }

        } else {
          // Sequential (default)
          const edge = orchestration.edges.find((e: any) => e.from === agentId);
          if (edge) { currentAgentId = edge.to; currentContext = output; }
          else currentAgentId = null;
        }

        if (!currentAgentId) {
          await step.run('mission-complete', async () => {
            const supabase = createServiceClient();
            console.log(`[Inngest] Mission complete.`);

            await supabase.from('events').insert({
              tenant_id: tenantId,
              event_type: 'mission.completed',
              entity_type: 'mission',
              entity_id: missionId,
              run_id: runId,
              payload: { finalOutput: output },
            });

            await transitionMissionStatus(missionId, tenantId, 'completed');

            const durationMs = Date.now() - startedAt;
            const { error: runErr } = await supabase.from('mission_runs').update({
              status: 'completed',
              completed_at: new Date().toISOString(),
              duration_ms: durationMs,
              agents_done: agentsDone,
              agents_failed: agentsFailed,
            }).eq('id', runId);
            if (runErr) console.warn('[Inngest] Failed to update mission_runs (non-fatal):', runErr.message);

            try {
              const { notifyMissionRunSummary } = await import('@/lib/services/notifications');
              await notifyMissionRunSummary(tenantId, mission.title, missionId, {
                runNumber, trigger, agentsTotal: agents.length, agentsDone, agentsFailed, durationMs,
              });
            } catch (e) {
              console.warn('[Inngest] Run summary notification failed (non-fatal):', e);
            }
          });
        }
      }

      return { success: true, missionId, runId };

    } catch (error: any) {
      if (error.message === 'PausedForApproval') {
        await step.run('pause-for-approval', async () => {
          await updateRun({ status: 'paused', agents_done: agentsDone, agents_failed: agentsFailed });
          try {
            const { notifyMissionStatus } = await import('@/lib/services/notifications');
            await notifyMissionStatus(tenantId, mission.title, missionId, 'needs_approval');
          } catch (e) {
            console.warn('[Inngest] Notification failed:', e);
          }
        });
        return { success: false, reason: 'paused_for_approval' };
      }

      if (error.message === 'InsufficientCredits') {
        await updateRun({ status: 'paused', agents_done: agentsDone, agents_failed: agentsFailed });
        return { success: false, reason: 'insufficient_credits' };
      }

      await step.run('mission-failed', async () => {
        const supabase = createServiceClient();
        console.error(`[Inngest] Mission failed:`, error.message);

        await supabase.from('events').insert({
          tenant_id: tenantId,
          event_type: 'mission.failed',
          entity_type: 'mission',
          entity_id: missionId,
          run_id: runId,
          payload: { error: error.message },
        });

        await transitionMissionStatus(missionId, tenantId, 'failed');

        const durationMs = Date.now() - startedAt;
        const { error: runErr } = await supabase.from('mission_runs').update({
          status: 'failed',
          completed_at: new Date().toISOString(),
          duration_ms: durationMs,
          agents_done: agentsDone,
          agents_failed: agentsFailed + 1,
        }).eq('id', runId);
        if (runErr) console.warn('[Inngest] Failed to update mission_runs (non-fatal):', runErr.message);

        try {
          const { notifyMissionStatus } = await import('@/lib/services/notifications');
          await notifyMissionStatus(tenantId, mission.title, missionId, 'failed');
        } catch (e) {
          console.warn('[Inngest] Notification failed:', e);
        }
      });

      throw error; // Let Inngest handle the retry
    }
  }
);

// ═══════════════════════════════════════════════════════════
// Inngest Function: Generate Blueprint in Background
// ═══════════════════════════════════════════════════════════

export const generateBlueprintBackground = inngest.createFunction(
  {
    id: 'generate-blueprint',
    name: 'Generate Blueprint (Background)',
    retries: 1,
    triggers: [{ event: 'mission/blueprint.generate' }],
  },
  async ({ event, step }) => {
    const { jobId, intent, tenantId, files } = event.data;
    const supabase = createServiceClient();

    const updateJobStatus = async (status: string, data: Record<string, any> = {}) => {
      await supabase.from('events').insert({
        tenant_id: tenantId,
        event_type: 'blueprint.job_update',
        entity_type: 'blueprint_job',
        entity_id: jobId,
        payload: { jobId, status, ...data, updatedAt: new Date().toISOString() },
      });
    };

    try {
      // ── Step 1: Pre-flight — tool check + initial status (fast) ──
      await step.run('pre-flight', async () => {
        await updateJobStatus('processing', { step: '🔍 Analyzing your goal...' });

        // Check which tools the tenant has connected
        const { data: perms } = await supabase
          .from('tenant_permissions')
          .select('provider')
          .eq('tenant_id', tenantId);

        const toolList = perms?.length
          ? perms.map((p: any) => p.provider).slice(0, 3).join(', ')
          : null;

        await updateJobStatus('processing', {
          step: toolList
            ? `🔌 Connected tools ready: ${toolList}`
            : '🔌 No connectors needed — reading only',
        });
      });

      // ── Step 2: LLM generation (the slow step — 15-30s) ──
      const discoveryResult = await step.run('generate-mission', async () => {
        await updateJobStatus('processing', { step: '🤖 AI architect is designing your agent team...' });

        const { generateMissionJSON } = await import('@/lib/services/intake');
        const result = await generateMissionJSON(intent, tenantId, files);

        if (result.isDiscovery && result.question) {
          return { type: 'discovery' as const, question: result.question };
        }
        if (!result.mission) throw new Error('Blueprint generation returned empty.');

        // Fire a descriptive "designed" message with real agent names so the
        // frontend can show them in the live log before the blueprint loads.
        const mission = result.mission;
        const roles = (mission.agents as any[]).slice(0, 4).map((a) => a.role);
        const roleStr = roles.join(' → ');
        const extra = mission.agents.length > 4 ? ` + ${mission.agents.length - 4} more` : '';
        await updateJobStatus('processing', {
          step: `📐 ${mission.agents.length}-agent pipeline designed: ${roleStr}${extra}`,
        });

        return { type: 'blueprint' as const, mission, rawLLMOutput: result.rawLLMOutput };
      });

      // ── Discovery flow ──
      if (discoveryResult.type === 'discovery') {
        await step.run('save-discovery', async () => {
          await updateJobStatus('discovery', { question: discoveryResult.question });
        });
        return { success: true, jobId, type: 'discovery' };
      }

      // ── Step 3: Validate + save ──
      await step.run('save-blueprint', async () => {
        await updateJobStatus('processing', { step: '✅ Validating blueprint structure...' });
        // Brief pause so SSE can pick up the validation message before completed fires
        await new Promise<void>((r) => setTimeout(r, 1200));

        const mission = discoveryResult.mission;
        await updateJobStatus('completed', {
          blueprint: mission,
          rawLLMOutput: discoveryResult.rawLLMOutput,
          meta: {
            agentCount: mission.agents.length,
            pattern: mission.orchestration.pattern,
            timeoutSeconds: mission.orchestration.timeoutSeconds,
          },
        });
      });

      await step.run('deduct-credit', async () => {
        // Blueprint generation makes 3 LLM calls: main generation + action name validation (4.6)
        // + parameter validation (4.7). Charge all three at pro tier (12 × 3 = 36 credits).
        const { deductCredits, CREDIT_COSTS } = await import('@/lib/middleware/billing');
        await deductCredits(tenantId, CREDIT_COSTS.llm_call_pro * 3, 'blueprint_generation').catch(() => {});
      });

      return { success: true, jobId, type: 'blueprint' };

    } catch (error: any) {
      const rawMsg: string = error.message || 'Unknown error';
      const isCircuitOpen = rawMsg.includes('Circuit breaker OPEN') || rawMsg.includes('Circuit is OPEN');

      await step.run('save-error', async () => {
        let userMsg = rawMsg;
        if (isCircuitOpen) {
          userMsg = "We're briefly managing system load — please wait 30 seconds and try again.";
        } else if (rawMsg.includes('No LLM provider available')) {
          userMsg = 'AI services are temporarily unavailable. Please try again in a moment.';
        } else if (rawMsg.toLowerCase().includes('rate limit') || rawMsg.includes('429')) {
          userMsg = 'Too many requests right now — please wait a moment and try again.';
        }
        await updateJobStatus('failed', { error: userMsg });
      });

      // Circuit-open errors must not be retried — each retry re-trips the circuit.
      if (isCircuitOpen) throw new NonRetriableError(rawMsg);
      throw error;
    }
  }
);
